I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/options.rpy", line 197, in script
    define config.has_autosave = false
  File "game/options.rpy", line 197, in <module>
    define config.has_autosave = false
NameError: name 'false' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/options.rpy", line 197, in script
    define config.has_autosave = false
  File "E:\renpy-8.1.1-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "E:\renpy-8.1.1-sdk\renpy\ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "E:\renpy-8.1.1-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/options.rpy", line 197, in <module>
    define config.has_autosave = false
NameError: name 'false' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
Sprites 1.0
Sun Nov  5 06:51:18 2023
