I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/sceen_ch0.rpy", line 9, in script
    scene bg sc0_2 with easein(1.0)
  File "game/sceen_ch0.rpy", line 9, in <module>
    scene bg sc0_2 with easein(1.0)
NameError: name 'easein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/sceen_ch0.rpy", line 9, in script
    scene bg sc0_2 with easein(1.0)
  File "E:\renpy-8.1.1-sdk\renpy\ast.py", line 1674, in execute
    paired = renpy.python.py_eval(self.paired)
  File "E:\renpy-8.1.1-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "E:\renpy-8.1.1-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/sceen_ch0.rpy", line 9, in <module>
    scene bg sc0_2 with easein(1.0)
NameError: name 'easein' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
Sprites 1.0
Fri Sep 29 00:37:06 2023
